{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "\n",
    "from sklearn import preprocessing\n",
    "from sklearn.cluster import KMeans"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.read_csv(\"dataset2.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id</th>\n",
       "      <th>date</th>\n",
       "      <th>time</th>\n",
       "      <th>lat</th>\n",
       "      <th>long</th>\n",
       "      <th>country</th>\n",
       "      <th>city</th>\n",
       "      <th>area</th>\n",
       "      <th>direction</th>\n",
       "      <th>dist</th>\n",
       "      <th>depth</th>\n",
       "      <th>xm</th>\n",
       "      <th>md</th>\n",
       "      <th>richter</th>\n",
       "      <th>mw</th>\n",
       "      <th>ms</th>\n",
       "      <th>mb</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2.000000e+13</td>\n",
       "      <td>2003.05.20</td>\n",
       "      <td>12:17:44 AM</td>\n",
       "      <td>39.04</td>\n",
       "      <td>40.38</td>\n",
       "      <td>turkey</td>\n",
       "      <td>bingol</td>\n",
       "      <td>baliklicay</td>\n",
       "      <td>west</td>\n",
       "      <td>0.1</td>\n",
       "      <td>10.0</td>\n",
       "      <td>4.1</td>\n",
       "      <td>4.1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2.010000e+13</td>\n",
       "      <td>2007.08.01</td>\n",
       "      <td>12:03:08 AM</td>\n",
       "      <td>40.79</td>\n",
       "      <td>30.09</td>\n",
       "      <td>turkey</td>\n",
       "      <td>kocaeli</td>\n",
       "      <td>bayraktar_izmit</td>\n",
       "      <td>west</td>\n",
       "      <td>0.1</td>\n",
       "      <td>5.2</td>\n",
       "      <td>4.0</td>\n",
       "      <td>3.8</td>\n",
       "      <td>4.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1.980000e+13</td>\n",
       "      <td>1978.05.07</td>\n",
       "      <td>12:41:37 AM</td>\n",
       "      <td>38.58</td>\n",
       "      <td>27.61</td>\n",
       "      <td>turkey</td>\n",
       "      <td>manisa</td>\n",
       "      <td>hamzabeyli</td>\n",
       "      <td>south_west</td>\n",
       "      <td>0.1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.7</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2.000000e+13</td>\n",
       "      <td>1997.03.22</td>\n",
       "      <td>12:31:45 AM</td>\n",
       "      <td>39.47</td>\n",
       "      <td>36.44</td>\n",
       "      <td>turkey</td>\n",
       "      <td>sivas</td>\n",
       "      <td>kahvepinar_sarkisla</td>\n",
       "      <td>south_west</td>\n",
       "      <td>0.1</td>\n",
       "      <td>10.0</td>\n",
       "      <td>3.5</td>\n",
       "      <td>3.5</td>\n",
       "      <td>0.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2.000000e+13</td>\n",
       "      <td>2000.04.02</td>\n",
       "      <td>12:57:38 AM</td>\n",
       "      <td>40.80</td>\n",
       "      <td>30.24</td>\n",
       "      <td>turkey</td>\n",
       "      <td>sakarya</td>\n",
       "      <td>meseli_serdivan</td>\n",
       "      <td>south_west</td>\n",
       "      <td>0.1</td>\n",
       "      <td>7.0</td>\n",
       "      <td>4.3</td>\n",
       "      <td>4.3</td>\n",
       "      <td>0.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24002</th>\n",
       "      <td>2.020000e+13</td>\n",
       "      <td>2017.03.10</td>\n",
       "      <td>12:23:42 AM</td>\n",
       "      <td>37.50</td>\n",
       "      <td>38.48</td>\n",
       "      <td>turkey</td>\n",
       "      <td>adiyaman</td>\n",
       "      <td>kirmacik_samsat</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>13.0</td>\n",
       "      <td>4.2</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.2</td>\n",
       "      <td>4.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24003</th>\n",
       "      <td>2.020000e+13</td>\n",
       "      <td>2017.03.10</td>\n",
       "      <td>12:42:44 AM</td>\n",
       "      <td>40.47</td>\n",
       "      <td>35.84</td>\n",
       "      <td>turkey</td>\n",
       "      <td>amasya</td>\n",
       "      <td>kizoglu</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>5.6</td>\n",
       "      <td>3.6</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.5</td>\n",
       "      <td>3.6</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24004</th>\n",
       "      <td>2.020000e+13</td>\n",
       "      <td>2017.04.05</td>\n",
       "      <td>12:08:11 AM</td>\n",
       "      <td>38.63</td>\n",
       "      <td>27.57</td>\n",
       "      <td>turkey</td>\n",
       "      <td>manisa</td>\n",
       "      <td>cavusoglu</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>10.6</td>\n",
       "      <td>4.1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>4.0</td>\n",
       "      <td>4.1</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24005</th>\n",
       "      <td>2.020000e+13</td>\n",
       "      <td>2017.04.05</td>\n",
       "      <td>12:35:09 AM</td>\n",
       "      <td>38.65</td>\n",
       "      <td>27.55</td>\n",
       "      <td>turkey</td>\n",
       "      <td>manisa</td>\n",
       "      <td>cavusoglu</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>8.7</td>\n",
       "      <td>3.8</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.6</td>\n",
       "      <td>3.8</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24006</th>\n",
       "      <td>2.020000e+13</td>\n",
       "      <td>2017.04.05</td>\n",
       "      <td>12:25:25 AM</td>\n",
       "      <td>38.63</td>\n",
       "      <td>27.58</td>\n",
       "      <td>turkey</td>\n",
       "      <td>manisa</td>\n",
       "      <td>cavusoglu</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>9.0</td>\n",
       "      <td>3.5</td>\n",
       "      <td>0.0</td>\n",
       "      <td>3.4</td>\n",
       "      <td>3.5</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>24007 rows Ã— 17 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                 id        date         time    lat   long country      city  \\\n",
       "0      2.000000e+13  2003.05.20  12:17:44 AM  39.04  40.38  turkey    bingol   \n",
       "1      2.010000e+13  2007.08.01  12:03:08 AM  40.79  30.09  turkey   kocaeli   \n",
       "2      1.980000e+13  1978.05.07  12:41:37 AM  38.58  27.61  turkey    manisa   \n",
       "3      2.000000e+13  1997.03.22  12:31:45 AM  39.47  36.44  turkey     sivas   \n",
       "4      2.000000e+13  2000.04.02  12:57:38 AM  40.80  30.24  turkey   sakarya   \n",
       "...             ...         ...          ...    ...    ...     ...       ...   \n",
       "24002  2.020000e+13  2017.03.10  12:23:42 AM  37.50  38.48  turkey  adiyaman   \n",
       "24003  2.020000e+13  2017.03.10  12:42:44 AM  40.47  35.84  turkey    amasya   \n",
       "24004  2.020000e+13  2017.04.05  12:08:11 AM  38.63  27.57  turkey    manisa   \n",
       "24005  2.020000e+13  2017.04.05  12:35:09 AM  38.65  27.55  turkey    manisa   \n",
       "24006  2.020000e+13  2017.04.05  12:25:25 AM  38.63  27.58  turkey    manisa   \n",
       "\n",
       "                      area   direction  dist  depth   xm   md  richter   mw  \\\n",
       "0               baliklicay        west   0.1   10.0  4.1  4.1      0.0  NaN   \n",
       "1          bayraktar_izmit        west   0.1    5.2  4.0  3.8      4.0  NaN   \n",
       "2               hamzabeyli  south_west   0.1    0.0  3.7  0.0      0.0  NaN   \n",
       "3      kahvepinar_sarkisla  south_west   0.1   10.0  3.5  3.5      0.0  NaN   \n",
       "4          meseli_serdivan  south_west   0.1    7.0  4.3  4.3      0.0  NaN   \n",
       "...                    ...         ...   ...    ...  ...  ...      ...  ...   \n",
       "24002      kirmacik_samsat         NaN   NaN   13.0  4.2  0.0      4.2  4.0   \n",
       "24003              kizoglu         NaN   NaN    5.6  3.6  0.0      3.5  3.6   \n",
       "24004            cavusoglu         NaN   NaN   10.6  4.1  0.0      4.0  4.1   \n",
       "24005            cavusoglu         NaN   NaN    8.7  3.8  0.0      3.6  3.8   \n",
       "24006            cavusoglu         NaN   NaN    9.0  3.5  0.0      3.4  3.5   \n",
       "\n",
       "        ms   mb  \n",
       "0      0.0  0.0  \n",
       "1      0.0  0.0  \n",
       "2      0.0  3.7  \n",
       "3      0.0  0.0  \n",
       "4      0.0  0.0  \n",
       "...    ...  ...  \n",
       "24002  0.0  0.0  \n",
       "24003  0.0  0.0  \n",
       "24004  0.0  0.0  \n",
       "24005  0.0  0.0  \n",
       "24006  0.0  0.0  \n",
       "\n",
       "[24007 rows x 17 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "data = data[['date', 'time', 'lat', 'long', 'depth', 'md']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>date</th>\n",
       "      <th>time</th>\n",
       "      <th>lat</th>\n",
       "      <th>long</th>\n",
       "      <th>depth</th>\n",
       "      <th>md</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2003.05.20</td>\n",
       "      <td>12:17:44 AM</td>\n",
       "      <td>39.04</td>\n",
       "      <td>40.38</td>\n",
       "      <td>10.0</td>\n",
       "      <td>4.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2007.08.01</td>\n",
       "      <td>12:03:08 AM</td>\n",
       "      <td>40.79</td>\n",
       "      <td>30.09</td>\n",
       "      <td>5.2</td>\n",
       "      <td>3.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1978.05.07</td>\n",
       "      <td>12:41:37 AM</td>\n",
       "      <td>38.58</td>\n",
       "      <td>27.61</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>1997.03.22</td>\n",
       "      <td>12:31:45 AM</td>\n",
       "      <td>39.47</td>\n",
       "      <td>36.44</td>\n",
       "      <td>10.0</td>\n",
       "      <td>3.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2000.04.02</td>\n",
       "      <td>12:57:38 AM</td>\n",
       "      <td>40.80</td>\n",
       "      <td>30.24</td>\n",
       "      <td>7.0</td>\n",
       "      <td>4.3</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "         date         time    lat   long  depth   md\n",
       "0  2003.05.20  12:17:44 AM  39.04  40.38   10.0  4.1\n",
       "1  2007.08.01  12:03:08 AM  40.79  30.09    5.2  3.8\n",
       "2  1978.05.07  12:41:37 AM  38.58  27.61    0.0  0.0\n",
       "3  1997.03.22  12:31:45 AM  39.47  36.44   10.0  3.5\n",
       "4  2000.04.02  12:57:38 AM  40.80  30.24    7.0  4.3"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_9290/2592514848.py:12: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  data['Timestamp'] = timestamp.values\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>lat</th>\n",
       "      <th>long</th>\n",
       "      <th>depth</th>\n",
       "      <th>md</th>\n",
       "      <th>Timestamp</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "Empty DataFrame\n",
       "Columns: [lat, long, depth, md, Timestamp]\n",
       "Index: []"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import datetime\n",
    "import time\n",
    "\n",
    "timestamp = []\n",
    "for d, t in zip(data['date'], data['time']):\n",
    "    try:\n",
    "        ts = datetime.datetime.strptime(d+' '+t, '%m/%d/%Y %H:%M:%S')\n",
    "        timestamp.append(time.mktime(ts.timetuple()))\n",
    "    except ValueError:\n",
    "        timestamp.append('ValueError')\n",
    "timestamp = pd.Series(timestamp)\n",
    "data['Timestamp'] = timestamp.values\n",
    "final_data = data.drop(['date','time'],axis=1)\n",
    "final_data = final_data[final_data.Timestamp != 'ValueError']\n",
    "final_data.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import plotly.graph_objects as go\n",
    "\n",
    "data.head()\n",
    "\n",
    "fig = go.Figure(data = go.Scattergeo(\n",
    "    lon = data[\"long\"],\n",
    "    lat = data[\"lat\"],\n",
    "    text = data[\"date\"],\n",
    "    mode = \"markers\",\n",
    "    marker = dict(\n",
    "        size = 12,\n",
    "        opacity = 0.8,\n",
    "        reversescale = True,\n",
    "        autocolorscale = True,\n",
    "        symbol = 'circle',\n",
    "        line = dict(\n",
    "            width = 1,\n",
    "            color = 'rgba(102, 102, 102)'\n",
    "        ),\n",
    "        cmin = 0,\n",
    "        color = data['md'],\n",
    "        cmax = data['md'].max(),\n",
    "        colorbar_title = \"Magnitude\"\n",
    "    )\n",
    "))\n",
    "\n",
    "fig.update_layout(\n",
    "    title = \"Earthquakes in Turkey\",\n",
    "    geo = dict(\n",
    "        scope = \"world\",\n",
    "        showland = True,\n",
    "    )\n",
    ")\n",
    "\n",
    "fig.write_html('first_figure.html', auto_open=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "(19205, 3) (4802, 3) (19205, 2) (4802, 3)\n"
     ]
    }
   ],
   "source": [
    "X = data[['date', 'lat', 'long']]\n",
    "y = data[['md', 'depth']]\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "print(X_train.shape, X_test.shape, y_train.shape, X_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-10-24 20:45:13.320436: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:13.320522: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n"
     ]
    }
   ],
   "source": [
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "\n",
    "def create_model(neurons, activation, optimizer, loss):\n",
    "    model = Sequential()\n",
    "    model.add(Dense(neurons, activation=activation, input_shape=(3,)))\n",
    "    model.add(Dense(neurons, activation=activation))\n",
    "    model.add(Dense(2, activation='softmax'))\n",
    "    \n",
    "    model.compile(optimizer=optimizer, loss=loss, metrics=['accuracy'])\n",
    "    \n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "\n",
    "model = KerasClassifier(build_fn=create_model, verbose=0)\n",
    "\n",
    "# neurons = [16, 64, 128, 256]\n",
    "neurons = [16]\n",
    "# batch_size = [10, 20, 50, 100]\n",
    "batch_size = [10]\n",
    "epochs = [10]\n",
    "# activation = ['relu', 'tanh', 'sigmoid', 'hard_sigmoid', 'linear', 'exponential']\n",
    "activation = ['sigmoid', 'relu']\n",
    "# optimizer = ['SGD', 'RMSprop', 'Adagrad', 'Adadelta', 'Adam', 'Adamax', 'Nadam']\n",
    "optimizer = ['SGD', 'Adadelta']\n",
    "loss = ['squared_hinge']\n",
    "\n",
    "param_grid = dict(neurons=neurons, batch_size=batch_size, epochs=epochs, activation=activation, optimizer=optimizer, loss=loss)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-10-24 20:45:19.923302: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:19.923779: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-10-24 20:45:19.981251: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:19.982059: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-10-24 20:45:20.256212: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:20.257018: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-10-24 20:45:20.306496: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:20.309565: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-10-24 20:45:20.387189: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:20.388103: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-10-24 20:45:20.681110: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:20.683451: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-10-24 20:45:20.779923: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:20.782719: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-10-24 20:45:20.946335: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:20.948525: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.\n",
      "2021-10-24 20:45:29.404536: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:29.404665: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:29.404724: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:29.406743: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2021-10-24 20:45:29.478113: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:29.481152: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:29.481961: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:29.483218: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "2021-10-24 20:45:30.541141: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:30.541244: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:30.541293: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:30.542094: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "6696   2007.03.02  38.38  39.27\n",
      "3180   2001.08.08  40.79  30.81\n",
      "15089  1984.10.05  40.59  28.32\n",
      "17806  1995.05.04  36.43  27.35\n",
      "8275   2017.02.07  39.52  26.07\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "17198  1992.01.12  36.56  25.43\n",
      "16882  1991.01.27  39.61  23.81\n",
      "11804  1970.05.14  43.00  47.00\n",
      "22017  2013.04.03  34.85  23.16\n",
      "1496   1999.12.28  39.88  38.28\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "17198  1992.01.12  36.56  25.43\n",
      "16882  1991.01.27  39.61  23.81\n",
      "11804  1970.05.14  43.00  47.00\n",
      "22017  2013.04.03  34.85  23.16\n",
      "1496   1999.12.28  39.88  38.28\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "2021-10-24 20:45:31.188950: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:31.189162: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:31.189234: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:31.190348: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2021-10-24 20:45:31.224604: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:31.226464: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:31.232926: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:31.235316: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "2021-10-24 20:45:31.357683: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:31.357866: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:31.357924: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:31.358706: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2021-10-24 20:45:31.368604: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:31.369899: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:31.370051: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:31.371381: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "2021-10-24 20:45:31.430436: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:31.431236: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:31.431887: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:31.433165: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "6696   2007.03.02  38.38  39.27\n",
      "3180   2001.08.08  40.79  30.81\n",
      "15089  1984.10.05  40.59  28.32\n",
      "17806  1995.05.04  36.43  27.35\n",
      "8275   2017.02.07  39.52  26.07\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "6696   2007.03.02  38.38  39.27\n",
      "3180   2001.08.08  40.79  30.81\n",
      "15089  1984.10.05  40.59  28.32\n",
      "17806  1995.05.04  36.43  27.35\n",
      "8275   2017.02.07  39.52  26.07\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "17198  1992.01.12  36.56  25.43\n",
      "16882  1991.01.27  39.61  23.81\n",
      "11804  1970.05.14  43.00  47.00\n",
      "22017  2013.04.03  34.85  23.16\n",
      "1496   1999.12.28  39.88  38.28\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "17198  1992.01.12  36.56  25.43\n",
      "16882  1991.01.27  39.61  23.81\n",
      "11804  1970.05.14  43.00  47.00\n",
      "22017  2013.04.03  34.85  23.16\n",
      "1496   1999.12.28  39.88  38.28\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "21575  2012.01.28  36.07  24.96\n",
      "5390   1996.05.26  38.39  39.08\n",
      "860    1994.01.31  38.73  27.47\n",
      "15795  1988.02.14  39.09  23.54\n",
      "23654  2017.06.12  38.91  26.28\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 106, in normalize_element\n",
      "    spec = type_spec_from_value(t, use_fallback=False)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 486, in type_spec_from_value\n",
      "    raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n",
      "TypeError: Could not build a TypeSpec for              date    lat   long\n",
      "3263   2011.10.26  38.64  43.74\n",
      "2754   2010.07.22  39.26  42.75\n",
      "7516   2001.01.10  36.97  31.33\n",
      "3572   2010.08.16  39.76  39.00\n",
      "16786  1990.10.08  39.01  23.63\n",
      "...           ...    ...    ...\n",
      "6696   2007.03.02  38.38  39.27\n",
      "3180   2001.08.08  40.79  30.81\n",
      "15089  1984.10.05  40.59  28.32\n",
      "17806  1995.05.04  36.43  27.35\n",
      "8275   2017.02.07  39.52  26.07\n",
      "\n",
      "[15364 rows x 3 columns] with type DataFrame\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/training.py\", line 1134, in fit\n",
      "    data_handler = data_adapter.get_data_handler(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1383, in get_data_handler\n",
      "    return DataHandler(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 1138, in __init__\n",
      "    self._adapter = adapter_cls(\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 322, in __init__\n",
      "    dataset = self.slice_inputs(indices_dataset, inputs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\", line 348, in slice_inputs\n",
      "    tf.data.Dataset.from_tensors(inputs).repeat()\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 606, in from_tensors\n",
      "    return TensorDataset(tensors)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\", line 3825, in __init__\n",
      "    element = structure.normalize_element(element)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\", line 111, in normalize_element\n",
      "    ops.convert_to_tensor(t, name=\"component_%d\" % i))\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\", line 163, in wrapped\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\", line 1566, in convert_to_tensor\n",
      "    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 346, in _constant_tensor_conversion_function\n",
      "    return constant(v, dtype=dtype, name=name)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 271, in constant\n",
      "    return _constant_impl(value, dtype, shape, name, verify_shape=False,\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 283, in _constant_impl\n",
      "    return _constant_eager_impl(ctx, value, dtype, shape, verify_shape)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 308, in _constant_eager_impl\n",
      "    t = convert_to_eager_tensor(value, ctx, dtype)\n",
      "  File \"/home/mayank/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\", line 106, in convert_to_eager_tensor\n",
      "    return ops.EagerTensor(value, ctx.device_name, dtype)\n",
      "ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/home/mayank/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning:\n",
      "\n",
      "One or more of the test scores are non-finite: [nan nan nan nan]\n",
      "\n",
      "2021-10-24 20:45:32.189613: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory\n",
      "2021-10-24 20:45:32.189669: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)\n",
      "2021-10-24 20:45:32.189696: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mayank-VivoBook): /proc/driver/nvidia/version does not exist\n",
      "2021-10-24 20:45:32.190114: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
      "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "Failed to convert a NumPy array to a Tensor (Unsupported object type float).",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\u001b[0m in \u001b[0;36mnormalize_element\u001b[0;34m(element, element_signature)\u001b[0m\n\u001b[1;32m    105\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mspec\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 106\u001b[0;31m           \u001b[0mspec\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtype_spec_from_value\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mt\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0muse_fallback\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    107\u001b[0m       \u001b[0;32mexcept\u001b[0m \u001b[0mTypeError\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\u001b[0m in \u001b[0;36mtype_spec_from_value\u001b[0;34m(element, use_fallback)\u001b[0m\n\u001b[1;32m    485\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 486\u001b[0;31m   raise TypeError(\"Could not build a TypeSpec for %r with type %s\" %\n\u001b[0m\u001b[1;32m    487\u001b[0m                   (element, type(element).__name__))\n",
      "\u001b[0;31mTypeError\u001b[0m: Could not build a TypeSpec for              date    lat   long\n3263   2011.10.26  38.64  43.74\n2754   2010.07.22  39.26  42.75\n7516   2001.01.10  36.97  31.33\n3572   2010.08.16  39.76  39.00\n16786  1990.10.08  39.01  23.63\n...           ...    ...    ...\n21575  2012.01.28  36.07  24.96\n5390   1996.05.26  38.39  39.08\n860    1994.01.31  38.73  27.47\n15795  1988.02.14  39.09  23.54\n23654  2017.06.12  38.91  26.28\n\n[19205 rows x 3 columns] with type DataFrame",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_9290/883923076.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0msklearn\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodel_selection\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mGridSearchCV\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0mgrid\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mGridSearchCV\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mestimator\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mparam_grid\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mparam_grid\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mn_jobs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m-\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mgrid_result\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mgrid\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Best: %f using %s\"\u001b[0m \u001b[0;34m%\u001b[0m \u001b[0;34m(\u001b[0m\u001b[0mgrid_result\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_score_\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mgrid_result\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_params_\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py\u001b[0m in \u001b[0;36minner_f\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     61\u001b[0m             \u001b[0mextra_args\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mall_args\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     62\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mextra_args\u001b[0m \u001b[0;34m<=\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 63\u001b[0;31m                 \u001b[0;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     64\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     65\u001b[0m             \u001b[0;31m# extra_args > 0\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[1;32m    878\u001b[0m             \u001b[0mrefit_start_time\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    879\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0my\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 880\u001b[0;31m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    881\u001b[0m             \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    882\u001b[0m                 \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mX\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, x, y, **kwargs)\u001b[0m\n\u001b[1;32m    217\u001b[0m       \u001b[0;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'Invalid shape for y: '\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mstr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshape\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    218\u001b[0m     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mn_classes_\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mclasses_\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 219\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0msuper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mKerasClassifier\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    220\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    221\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0mpredict\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/keras/wrappers/scikit_learn.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, x, y, **kwargs)\u001b[0m\n\u001b[1;32m    160\u001b[0m     \u001b[0mfit_args\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    161\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 162\u001b[0;31m     \u001b[0mhistory\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mfit_args\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    163\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    164\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mhistory\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/keras/engine/training.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)\u001b[0m\n\u001b[1;32m   1132\u001b[0m          \u001b[0mtraining_utils\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mRespectCompiledTrainableState\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1133\u001b[0m       \u001b[0;31m# Creates a `tf.data.Dataset` and handles batch and epoch iteration.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1134\u001b[0;31m       data_handler = data_adapter.get_data_handler(\n\u001b[0m\u001b[1;32m   1135\u001b[0m           \u001b[0mx\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1136\u001b[0m           \u001b[0my\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\u001b[0m in \u001b[0;36mget_data_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m   1381\u001b[0m   \u001b[0;32mif\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"model\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"_cluster_coordinator\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1382\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0m_ClusterCoordinatorDataHandler\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1383\u001b[0;31m   \u001b[0;32mreturn\u001b[0m \u001b[0mDataHandler\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1384\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1385\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model, steps_per_execution, distribute)\u001b[0m\n\u001b[1;32m   1136\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1137\u001b[0m     \u001b[0madapter_cls\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mselect_data_adapter\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1138\u001b[0;31m     self._adapter = adapter_cls(\n\u001b[0m\u001b[1;32m   1139\u001b[0m         \u001b[0mx\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1140\u001b[0m         \u001b[0my\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, x, y, sample_weights, sample_weight_modes, batch_size, epochs, steps, shuffle, **kwargs)\u001b[0m\n\u001b[1;32m    320\u001b[0m     \u001b[0mindices_dataset\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mindices_dataset\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mflat_map\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mslice_batch_indices\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    321\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 322\u001b[0;31m     \u001b[0mdataset\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mslice_inputs\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mindices_dataset\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minputs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    323\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    324\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mshuffle\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"batch\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/keras/engine/data_adapter.py\u001b[0m in \u001b[0;36mslice_inputs\u001b[0;34m(self, indices_dataset, inputs)\u001b[0m\n\u001b[1;32m    346\u001b[0m     dataset = tf.data.Dataset.zip((\n\u001b[1;32m    347\u001b[0m         \u001b[0mindices_dataset\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 348\u001b[0;31m         \u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mDataset\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_tensors\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minputs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrepeat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    349\u001b[0m     ))\n\u001b[1;32m    350\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\u001b[0m in \u001b[0;36mfrom_tensors\u001b[0;34m(tensors)\u001b[0m\n\u001b[1;32m    604\u001b[0m       \u001b[0mDataset\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0mA\u001b[0m\u001b[0;31m \u001b[0m\u001b[0;31m`\u001b[0m\u001b[0mDataset\u001b[0m\u001b[0;31m`\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    605\u001b[0m     \"\"\"\n\u001b[0;32m--> 606\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mTensorDataset\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtensors\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    607\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    608\u001b[0m   \u001b[0;34m@\u001b[0m\u001b[0mstaticmethod\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/data/ops/dataset_ops.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, element)\u001b[0m\n\u001b[1;32m   3823\u001b[0m   \u001b[0;32mdef\u001b[0m \u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0melement\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3824\u001b[0m     \u001b[0;34m\"\"\"See `Dataset.from_tensors()` for details.\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3825\u001b[0;31m     \u001b[0melement\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstructure\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mnormalize_element\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0melement\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3826\u001b[0m     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_structure\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstructure\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtype_spec_from_value\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0melement\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3827\u001b[0m     \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_tensors\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mstructure\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mto_tensor_list\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_structure\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0melement\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/data/util/structure.py\u001b[0m in \u001b[0;36mnormalize_element\u001b[0;34m(element, element_signature)\u001b[0m\n\u001b[1;32m    109\u001b[0m         \u001b[0;31m# the value. As a fallback try converting the value to a tensor.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    110\u001b[0m         normalized_components.append(\n\u001b[0;32m--> 111\u001b[0;31m             ops.convert_to_tensor(t, name=\"component_%d\" % i))\n\u001b[0m\u001b[1;32m    112\u001b[0m       \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    113\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mspec\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msparse_tensor\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSparseTensorSpec\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/profiler/trace.py\u001b[0m in \u001b[0;36mwrapped\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    161\u001b[0m         \u001b[0;32mwith\u001b[0m \u001b[0mTrace\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mtrace_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mtrace_kwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    162\u001b[0m           \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 163\u001b[0;31m       \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    164\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    165\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mwrapped\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py\u001b[0m in \u001b[0;36mconvert_to_tensor\u001b[0;34m(value, dtype, name, as_ref, preferred_dtype, dtype_hint, ctx, accepted_result_types)\u001b[0m\n\u001b[1;32m   1564\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1565\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mret\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1566\u001b[0;31m       \u001b[0mret\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconversion_func\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdtype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mas_ref\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mas_ref\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1567\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1568\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mret\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0mNotImplemented\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\u001b[0m in \u001b[0;36m_constant_tensor_conversion_function\u001b[0;34m(v, dtype, name, as_ref)\u001b[0m\n\u001b[1;32m    344\u001b[0m                                          as_ref=False):\n\u001b[1;32m    345\u001b[0m   \u001b[0m_\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mas_ref\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 346\u001b[0;31m   \u001b[0;32mreturn\u001b[0m \u001b[0mconstant\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mv\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdtype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mname\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    347\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    348\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\u001b[0m in \u001b[0;36mconstant\u001b[0;34m(value, dtype, shape, name)\u001b[0m\n\u001b[1;32m    269\u001b[0m     \u001b[0mValueError\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;32mif\u001b[0m \u001b[0mcalled\u001b[0m \u001b[0mon\u001b[0m \u001b[0ma\u001b[0m \u001b[0msymbolic\u001b[0m \u001b[0mtensor\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    270\u001b[0m   \"\"\"\n\u001b[0;32m--> 271\u001b[0;31m   return _constant_impl(value, dtype, shape, name, verify_shape=False,\n\u001b[0m\u001b[1;32m    272\u001b[0m                         allow_broadcast=True)\n\u001b[1;32m    273\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\u001b[0m in \u001b[0;36m_constant_impl\u001b[0;34m(value, dtype, shape, name, verify_shape, allow_broadcast)\u001b[0m\n\u001b[1;32m    281\u001b[0m       \u001b[0;32mwith\u001b[0m \u001b[0mtrace\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mTrace\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"tf.constant\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    282\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0m_constant_eager_impl\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mctx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mshape\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mverify_shape\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 283\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0m_constant_eager_impl\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mctx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mshape\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mverify_shape\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    284\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    285\u001b[0m   \u001b[0mg\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mops\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_default_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\u001b[0m in \u001b[0;36m_constant_eager_impl\u001b[0;34m(ctx, value, dtype, shape, verify_shape)\u001b[0m\n\u001b[1;32m    306\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0m_constant_eager_impl\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mctx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mshape\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mverify_shape\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    307\u001b[0m   \u001b[0;34m\"\"\"Creates a constant on the current device.\"\"\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 308\u001b[0;31m   \u001b[0mt\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mconvert_to_eager_tensor\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mctx\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    309\u001b[0m   \u001b[0;32mif\u001b[0m \u001b[0mshape\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    310\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0mt\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/.local/lib/python3.8/site-packages/tensorflow/python/framework/constant_op.py\u001b[0m in \u001b[0;36mconvert_to_eager_tensor\u001b[0;34m(value, ctx, dtype)\u001b[0m\n\u001b[1;32m    104\u001b[0m       \u001b[0mdtype\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdtypes\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mas_dtype\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdtype\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mas_datatype_enum\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    105\u001b[0m   \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 106\u001b[0;31m   \u001b[0;32mreturn\u001b[0m \u001b[0mops\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mEagerTensor\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdevice_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    107\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    108\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mValueError\u001b[0m: Failed to convert a NumPy array to a Tensor (Unsupported object type float)."
     ]
    }
   ],
   "source": [
    "from sklearn.model_selection import GridSearchCV\n",
    "grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1)\n",
    "grid_result = grid.fit(X_train, y_train)\n",
    "\n",
    "print(\"Best: %f using %s\" % (grid_result.best_score_, grid_result.best_params_))\n",
    "means = grid_result.cv_results_['mean_test_score']\n",
    "stds = grid_result.cv_results_['std_test_score']\n",
    "params = grid_result.cv_results_['params']\n",
    "for mean, stdev, param in zip(means, stds, params):\n",
    "    print(\"%f (%f) with: %r\" % (mean, stdev, param))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "90e5470ee8bd69c0c8c31460769dab0e797aa61395e7c573d1d3a8a9547b71d9"
  },
  "kernelspec": {
   "display_name": "Python 3.8.8 64-bit ('base': conda)",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
